# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\TuckerVana\PycharmProjects\GUI Project 2.0\PyGMI-master\PyGMI_files\Instruments_panels\FlowMeter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(1073, 812)
        self.monitor = QtWidgets.QCheckBox(Panel)
        self.monitor.setGeometry(QtCore.QRect(11, 61, 70, 20))
        self.monitor.setChecked(False)
        self.monitor.setObjectName("monitor")
        self.label_47 = QtWidgets.QLabel(Panel)
        self.label_47.setGeometry(QtCore.QRect(11, 88, 71, 16))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.refresh_rate = QtWidgets.QDoubleSpinBox(Panel)
        self.refresh_rate.setGeometry(QtCore.QRect(11, 111, 115, 22))
        self.refresh_rate.setMinimumSize(QtCore.QSize(91, 0))
        self.refresh_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.refresh_rate.setDecimals(1)
        self.refresh_rate.setMaximum(9999999.0)
        self.refresh_rate.setSingleStep(0.5)
        self.refresh_rate.setProperty("value", 2.0)
        self.refresh_rate.setObjectName("refresh_rate")
        self.f_disp_6 = QtWidgets.QLabel(Panel)
        self.f_disp_6.setGeometry(QtCore.QRect(12, 141, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.f_disp_6.setFont(font)
        self.f_disp_6.setAutoFillBackground(False)
        self.f_disp_6.setStyleSheet("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);")
        self.f_disp_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.f_disp_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.f_disp_6.setScaledContents(False)
        self.f_disp_6.setAlignment(QtCore.Qt.AlignCenter)
        self.f_disp_6.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.f_disp_6.setObjectName("f_disp_6")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(Panel)
        self.lcdNumber_6.setGeometry(QtCore.QRect(10, 200, 131, 91))
        self.lcdNumber_6.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.label = QtWidgets.QLabel(Panel)
        self.label.setGeometry(QtCore.QRect(150, 230, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Panel)
        self.label_2.setGeometry(QtCore.QRect(10, 290, 151, 91))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(3)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Panel)
        self.refresh_rate.valueChanged['QString'].connect(Panel.update_timer_timeout) # type: ignore
        self.monitor.stateChanged['int'].connect(Panel.monitor) # type: ignore
        self.monitor.stateChanged['int'].connect(self.label_2.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        _translate = QtCore.QCoreApplication.translate
        Panel.setWindowTitle(_translate("Panel", "FlowMeter"))
        self.monitor.setText(_translate("Panel", "Monitor"))
        self.label_47.setText(_translate("Panel", "Refresh rate"))
        self.refresh_rate.setSuffix(_translate("Panel", " secs"))
        self.f_disp_6.setText(_translate("Panel", "Flow Meter"))
        self.label.setText(_translate("Panel", "slm"))
        self.label_2.setText(_translate("Panel", "Status"))
